#!/usr/bin/env bash
set -euo pipefail

forge fmt --check 
solhint "**/*.sol" -w 0
slither ./
slither . --config-file slither_openzeppelin.config.json

forge clean && forge test

if ! bash jobs/check_coverage.sh; then
  echo "run this command to check coverage details with lcov: forge clean > /dev/null && forge build > /dev/null && forge coverage --report lcov && genhtml lcov.info --branch-coverage --output-dir coverage --ignore-errors category,category,inconsistent"
  exit 1
fi