name: CI-Lint-And-Test

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          forge soldeer install

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run tests
        run: |
          forge clean && forge test --gas-price 1000000000
        id: test

      - name: Check code coverage
        run: jobs/check_coverage.sh

  solhint:
    name: solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install solhint
        run: npm install -g solhint
      - name: Run lints
        run: |
          solhint "**/*.sol" -w 0

  slither:
    name: slither
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Install dependencies
        run: forge soldeer install
      - name: Run slither
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0
      - name: Run slither without ignoring openzeppelin
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0
        with:
          slither-config: slither_openzeppelin.config.json
