name: CI-Lint-And-Test

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install JavaScript dependencies
        run: |
          npm install --no-save @openzeppelin/upgrades-core keccak

      - name: Fix script permissions
        run: chmod -R +x node_modules/.bin

      - name: Install Forge dependencies
        run: |
          forge soldeer install

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run tests
        run: |
          export OZ_NO_VALIDATE=true
          forge clean && forge test
        id: test

      - name: Run tests with via-ir
        run: |
          export OZ_NO_VALIDATE=true
          forge clean && forge test --via-ir
        id: test-via-ir

      - name: Make coverage script executable
        run: chmod +x jobs/check_coverage.sh

      - name: Check code coverage
        run: jobs/check_coverage.sh

  solhint:
    name: solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install solhint
        run: npm install -g solhint

      - name: Run lints
        run: |
          solhint "**/*.sol" -w 0

  slither:
    name: slither
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Forge dependencies
        run: forge soldeer install

      - name: Run slither
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0

      - name: Run slither without ignoring dependencies
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0
        with:
          slither-config: slither_dependencies.config.json
